// Code generated by mockery v2.14.1. DO NOT EDIT.

package mocks

import (
	filtering "github.com/company/blanksvc/pkg/filtering"
	mock "github.com/stretchr/testify/mock"

	models "github.com/company/blanksvc/pkg/models"

	sorting "github.com/company/blanksvc/pkg/sorting"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CompleteTask provides a mock function with given fields: id
func (_m *Service) CompleteTask(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateTask provides a mock function with given fields: task
func (_m *Service) CreateTask(task *models.Task) (*models.Task, error) {
	ret := _m.Called(task)

	var r0 *models.Task
	if rf, ok := ret.Get(0).(func(*models.Task) *models.Task); ok {
		r0 = rf(task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.Task) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteTask provides a mock function with given fields: id
func (_m *Service) DeleteTask(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTask provides a mock function with given fields: id
func (_m *Service) GetTask(id string) (*models.Task, error) {
	ret := _m.Called(id)

	var r0 *models.Task
	if rf, ok := ret.Get(0).(func(string) *models.Task); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTasks provides a mock function with given fields: filter, sort, itemsOnPage, page
func (_m *Service) ListTasks(filter *filtering.Filter, sort *sorting.Sort, itemsOnPage int, page int) ([]models.Task, int64, error) {
	ret := _m.Called(filter, sort, itemsOnPage, page)

	var r0 []models.Task
	if rf, ok := ret.Get(0).(func(*filtering.Filter, *sorting.Sort, int, int) []models.Task); ok {
		r0 = rf(filter, sort, itemsOnPage, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Task)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(*filtering.Filter, *sorting.Sort, int, int) int64); ok {
		r1 = rf(filter, sort, itemsOnPage, page)
	} else {
		r1 = ret.Get(1).(int64)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(*filtering.Filter, *sorting.Sort, int, int) error); ok {
		r2 = rf(filter, sort, itemsOnPage, page)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// UncompleteTask provides a mock function with given fields: id
func (_m *Service) UncompleteTask(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTask provides a mock function with given fields: task
func (_m *Service) UpdateTask(task *models.Task) (*models.Task, error) {
	ret := _m.Called(task)

	var r0 *models.Task
	if rf, ok := ret.Get(0).(func(*models.Task) *models.Task); ok {
		r0 = rf(task)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Task)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.Task) error); ok {
		r1 = rf(task)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewService(t mockConstructorTestingTNewService) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
